name: Build and test

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

# Must set Settings -> Actions -> General -> Workflow permissions to
# "Read and write permissions" 
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        arch: ["x86"]

    steps:
      - uses: actions/checkout@v3
  
      - name: Generate ZIP name and version string
        id: filename
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          GIT_VERSION="$(git describe --tags --always)"
          echo "version=${GIT_VERSION:1}" >> $GITHUB_OUTPUT
          echo "zipname=w64devkit-mini-for-patching" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build -t w64devkit .
          docker run --rm w64devkit > ${{ steps.filename.outputs.zipname }}.zip

        # https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - name: Prepare artifact
        run: |
          unzip ${{ steps.filename.outputs.zipname }}.zip
          7z a -t7z -m0=lzma2 -mx=9 -aoa ./w64devkit-mini-for-patching.7z ./w64devkit/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.filename.outputs.zipname }}
          path: w64devkit/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.filename.outputs.version }}
          files: |
            w64devkit*.zip
            w64devkit*.7z
          draft: true
