name: Build and test

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

# Must set Settings -> Actions -> General -> Workflow permissions to
# "Read and write permissions" 
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: ["i686"]
        flavor: [""]

    steps:
      - uses: actions/checkout@v3

      - name: Generate ZIP name and version string
        id: filename
        env:
          ARCH: ${{ matrix.arch }}
          FLAVOR: ${{ matrix.flavor }}
        run: |
          GIT_VERSION="$(git describe --tags --always)"
          echo "version=${GIT_VERSION:1}" >> $GITHUB_OUTPUT
          echo "zipname=w64devkit${ARCH:+-$ARCH}${FLAVOR:+-$FLAVOR}-${GIT_VERSION:1}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build -t w64devkit .
          docker run --rm w64devkit > ${{ steps.filename.outputs.zipname }}.zip

        # https://github.com/actions/upload-artifact#zipped-artifact-downloads
      - name: Prepare artifact
        run: |
          unzip ${{ steps.filename.outputs.zipname }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.filename.outputs.zipname }}
          path: w64devkit/*
